
import React, { useState, useEffect, useMemo } from 'react';
import { 
  LayoutDashboard, 
  CalendarClock, 
  Wallet, 
  PlusCircle, 
  TrendingUp, 
  Fuel, 
  MapPin, 
  User, 
  Clock,
  ArrowRightLeft,
  Trash2,
  CheckCircle2,
  History,
  CheckCircle,
  Lock
} from 'lucide-react';
import { Job, ScheduledJob, Expense, ExpenseType } from './types';

// Components
import JobForm from './components/JobForm';
import ScheduledJobForm from './components/ScheduledJobForm';
import ExpenseForm from './components/ExpenseForm';
import StatsOverview from './components/StatsOverview';
import ConfirmationModal from './components/ConfirmationModal';

const App: React.FC = () => {
  const [view, setView] = useState<'daily' | 'scheduled' | 'stats'>('daily');
  
  // Modal State
  const [modalConfig, setModalConfig] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    confirmText: string;
    type: 'danger' | 'success' | 'info';
    onConfirm: () => void;
  }>({
    isOpen: false,
    title: '',
    message: '',
    confirmText: '',
    type: 'info',
    onConfirm: () => {}
  });

  // State from LocalStorage
  const [jobs, setJobs] = useState<Job[]>(() => {
    const saved = localStorage.getItem('logistics_jobs');
    return saved ? JSON.parse(saved) : [];
  });
  
  const [scheduledJobs, setScheduledJobs] = useState<ScheduledJob[]>(() => {
    const saved = localStorage.getItem('logistics_scheduled');
    return saved ? JSON.parse(saved) : [];
  });

  const [finishedJobs, setFinishedJobs] = useState<ScheduledJob[]>(() => {
    const saved = localStorage.getItem('logistics_finished');
    return saved ? JSON.parse(saved) : [];
  });
  
  const [expenses, setExpenses] = useState<Expense[]>(() => {
    const saved = localStorage.getItem('logistics_expenses');
    return saved ? JSON.parse(saved) : [];
  });

  // Sync to LocalStorage
  useEffect(() => localStorage.setItem('logistics_jobs', JSON.stringify(jobs)), [jobs]);
  useEffect(() => localStorage.setItem('logistics_scheduled', JSON.stringify(scheduledJobs)), [scheduledJobs]);
  useEffect(() => localStorage.setItem('logistics_finished', JSON.stringify(finishedJobs)), [finishedJobs]);
  useEffect(() => localStorage.setItem('logistics_expenses', JSON.stringify(expenses)), [expenses]);

  // Handlers
  const addJob = (job: Omit<Job, 'id' | 'date' | 'timestamp'>) => {
    const newJob: Job = {
      ...job,
      id: Math.random().toString(36).substr(2, 9),
      date: new Date().toISOString(),
      timestamp: Date.now()
    };
    setJobs(prev => [newJob, ...prev]);
  };

  const addScheduledJob = (job: Omit<ScheduledJob, 'id'>) => {
    const newJob: ScheduledJob = {
      ...job,
      id: Math.random().toString(36).substr(2, 9)
    };
    setScheduledJobs(prev => [...prev, newJob].sort((a, b) => {
      const dateTimeA = new Date(`${a.date}T${a.time}`).getTime();
      const dateTimeB = new Date(`${b.date}T${b.time}`).getTime();
      return dateTimeA - dateTimeB;
    }));
  };

  const handleConfirmArrivalAction = (job: ScheduledJob) => {
    setModalConfig({
      isOpen: true,
      title: 'Varış Onayla',
      message: `${job.passengerName} isimli yolcunun yolculuğunun tamamlandığını onaylıyor musunuz? Bu işlem ${job.fee} TL tutarı kasanıza gelir olarak ekleyecektir.`,
      confirmText: 'Onayla',
      type: 'success',
      onConfirm: () => {
        const newDailyJob: Job = {
          id: job.id + '_confirmed',
          from: job.from,
          to: job.to,
          amount: job.fee,
          date: new Date().toISOString(),
          timestamp: Date.now(),
          isAutoGenerated: true
        };
        setJobs(prev => [newDailyJob, ...prev]);
        setFinishedJobs(prev => [job, ...prev]);
        setScheduledJobs(prev => prev.filter(sj => sj.id !== job.id));
      }
    });
  };

  const handleDeleteScheduledJobAction = (job: ScheduledJob) => {
    setModalConfig({
      isOpen: true,
      title: 'İşi Sil',
      message: `${job.passengerName} isimli yolcu için planlanan bu işi silmek istediğinize emin misiniz?`,
      confirmText: 'Sil',
      type: 'danger',
      onConfirm: () => {
        setScheduledJobs(prev => prev.filter(sj => sj.id !== job.id));
      }
    });
  };

  const addExpenses = (newExpenses: { type: ExpenseType; amount: number }[]) => {
    const filtered = newExpenses.filter(e => e.amount > 0);
    const mapped: Expense[] = filtered.map(e => ({
      ...e,
      id: Math.random().toString(36).substr(2, 9),
      date: new Date().toISOString()
    }));
    setExpenses(prev => [...mapped, ...prev]);
  };

  const deleteJob = (id: string) => setJobs(prev => prev.filter(j => j.id !== id));
  const deleteExpense = (id: string) => setExpenses(prev => prev.filter(e => e.id !== id));
  const clearFinished = () => {
    setModalConfig({
      isOpen: true,
      title: 'Arşivi Temizle',
      message: 'Tüm biten iş geçmişini silmek üzeresiniz. Bu işlem geri alınamaz.',
      confirmText: 'Temizle',
      type: 'danger',
      onConfirm: () => setFinishedJobs([])
    });
  };

  const getRemainingTime = (date: string, time: string) => {
    const target = new Date(`${date}T${time}`).getTime();
    const now = new Date().getTime();
    const diff = target - now;

    if (diff < 0) return "Süresi Doldu";

    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    const days = Math.floor(hours / 24);

    if (days > 0) return `${days} gün ${hours % 24} sa`;
    if (hours > 0) return `${hours} sa ${minutes} dk`;
    return `${minutes} dk kaldı`;
  };

  const isJobExpired = (date: string, time: string) => {
    const target = new Date(`${date}T${time}`).getTime();
    return Date.now() >= target;
  };

  return (
    <div className="min-h-screen bg-slate-50 pb-20 md:pb-0">
      <ConfirmationModal 
        isOpen={modalConfig.isOpen}
        onClose={() => setModalConfig(prev => ({ ...prev, isOpen: false }))}
        onConfirm={modalConfig.onConfirm}
        title={modalConfig.title}
        message={modalConfig.message}
        confirmText={modalConfig.confirmText}
        type={modalConfig.type}
      />

      <nav className="fixed bottom-0 left-0 w-full bg-white border-t border-slate-200 flex justify-around p-3 md:top-0 md:bottom-auto md:justify-start md:px-8 md:gap-8 z-50 shadow-lg">
        <button onClick={() => setView('daily')} className={`flex flex-col md:flex-row items-center gap-1 md:gap-2 px-4 py-2 rounded-xl transition-all ${view === 'daily' ? 'bg-blue-50 text-blue-600' : 'text-slate-500 hover:text-slate-800'}`}>
          <LayoutDashboard size={20} />
          <span className="text-xs md:text-sm font-semibold">Günlük İşler</span>
        </button>
        <button onClick={() => setView('scheduled')} className={`flex flex-col md:flex-row items-center gap-1 md:gap-2 px-4 py-2 rounded-xl transition-all ${view === 'scheduled' ? 'bg-blue-50 text-blue-600' : 'text-slate-500 hover:text-slate-800'}`}>
          <CalendarClock size={20} />
          <span className="text-xs md:text-sm font-semibold">İleri Tarihli</span>
        </button>
        <button onClick={() => setView('stats')} className={`flex flex-col md:flex-row items-center gap-1 md:gap-2 px-4 py-2 rounded-xl transition-all ${view === 'stats' ? 'bg-blue-50 text-blue-600' : 'text-slate-500 hover:text-slate-800'}`}>
          <Wallet size={20} />
          <span className="text-xs md:text-sm font-semibold">Ciro & Analiz</span>
        </button>
      </nav>

      <main className="max-w-6xl mx-auto px-4 pt-4 md:pt-24 pb-8">
        {view === 'daily' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-4 space-y-6">
              <JobForm onAdd={addJob} />
              <ExpenseForm onAdd={addExpenses} />
            </div>
            <div className="lg:col-span-8">
              <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                <div className="p-4 bg-slate-50 border-b border-slate-200 flex justify-between items-center">
                  <h2 className="font-bold text-slate-800 flex items-center gap-2">
                    <TrendingUp size={18} className="text-green-500" />
                    Bugünkü Hareketler
                  </h2>
                </div>
                <div className="divide-y divide-slate-100 max-h-[600px] overflow-y-auto">
                  {jobs.length === 0 && expenses.length === 0 ? (
                    <div className="p-12 text-center text-slate-400">Henüz bir hareket girilmedi.</div>
                  ) : (
                    <>
                      {jobs.map(job => (
                        <div key={job.id} className="p-4 flex justify-between items-center hover:bg-slate-50 transition-colors">
                          <div className="flex gap-4 items-center">
                            <div className={`p-2 rounded-lg ${job.isAutoGenerated ? 'bg-green-50 text-green-600' : 'bg-blue-50 text-blue-600'}`}>
                              {job.isAutoGenerated ? <CheckCircle2 size={18} /> : <ArrowRightLeft size={18} />}
                            </div>
                            <div>
                              <div className="font-medium text-slate-900">{job.from} → {job.to}</div>
                              <div className="text-xs text-slate-500">
                                {new Date(job.date).toLocaleTimeString('tr-TR')} {job.isAutoGenerated && '(Planlıdan Aktarıldı)'}
                              </div>
                            </div>
                          </div>
                          <div className="flex items-center gap-4">
                            <div className="font-bold text-green-600">+{job.amount.toLocaleString('tr-TR')} ₺</div>
                            <button onClick={() => deleteJob(job.id)} className="p-2 text-slate-300 hover:text-red-500 transition-colors">
                              <Trash2 size={16} />
                            </button>
                          </div>
                        </div>
                      ))}
                      {expenses.map(expense => (
                        <div key={expense.id} className="p-4 flex justify-between items-center hover:bg-slate-50 transition-colors">
                          <div className="flex gap-4 items-center">
                            <div className="p-2 bg-red-50 text-red-600 rounded-lg">
                              <Fuel size={18} />
                            </div>
                            <div>
                              <div className="font-medium text-slate-900">{expense.type} Gideri</div>
                              <div className="text-xs text-slate-500">{new Date(expense.date).toLocaleTimeString('tr-TR')}</div>
                            </div>
                          </div>
                          <div className="flex items-center gap-4">
                            <div className="font-bold text-red-600">-{expense.amount.toLocaleString('tr-TR')} ₺</div>
                            <button onClick={() => deleteExpense(expense.id)} className="p-2 text-slate-300 hover:text-red-500 transition-colors">
                              <Trash2 size={16} />
                            </button>
                          </div>
                        </div>
                      ))}
                    </>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {view === 'scheduled' && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            <div className="lg:col-span-4">
              <ScheduledJobForm onAdd={addScheduledJob} />
            </div>
            <div className="lg:col-span-8 space-y-8">
              <section className="space-y-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-xl font-bold text-slate-800">Yaklaşan İşler</h2>
                  <span className="bg-blue-100 text-blue-700 text-xs font-bold px-2 py-1 rounded-full">{scheduledJobs.length} Kayıt</span>
                </div>
                {scheduledJobs.length === 0 ? (
                  <div className="bg-white rounded-2xl p-12 text-center border border-dashed border-slate-300 text-slate-400">Planlanmış bir iş bulunmuyor.</div>
                ) : (
                  <div className="grid grid-cols-1 gap-4">
                    {scheduledJobs.map(job => {
                      const expired = isJobExpired(job.date, job.time);
                      return (
                        <div key={job.id} className="bg-white p-5 rounded-2xl shadow-sm border border-slate-200 flex flex-col md:flex-row md:items-center justify-between gap-4">
                          <div className="flex items-start gap-4">
                            <div className="flex flex-col items-center justify-center bg-blue-50 p-3 rounded-xl min-w-[70px]">
                              <span className="text-xs font-bold text-blue-400 uppercase">{new Date(job.date).toLocaleDateString('tr-TR', { month: 'short' })}</span>
                              <span className="text-2xl font-black text-blue-700">{new Date(job.date).getDate()}</span>
                            </div>
                            <div>
                              <div className="flex items-center gap-2 mb-1">
                                <User size={16} className="text-slate-400" />
                                <span className="font-bold text-slate-900">{job.passengerName}</span>
                              </div>
                              <div className="flex items-center gap-2 text-sm text-slate-600">
                                <MapPin size={14} className="text-blue-500" />
                                <span>{job.from} → {job.to}</span>
                              </div>
                              <div className="flex items-center gap-4 text-sm mt-2">
                                  <span className="flex items-center gap-1 text-slate-500"><Clock size={14} /> {job.time}</span>
                                  <span className={`font-bold px-2 py-0.5 rounded text-xs ${expired ? 'text-red-500 bg-red-50' : 'text-orange-500 bg-orange-50'}`}>
                                    {getRemainingTime(job.date, job.time)}
                                  </span>
                              </div>
                            </div>
                          </div>
                          <div className="flex items-center justify-between md:flex-col md:items-end gap-3 border-t md:border-t-0 pt-3 md:pt-0 border-slate-100">
                            <div className="text-xl font-black text-green-600">{job.fee.toLocaleString('tr-TR')} ₺</div>
                            <div className="flex gap-2">
                              <button 
                                onClick={() => handleConfirmArrivalAction(job)}
                                disabled={!expired}
                                className={`flex items-center gap-1 text-white text-xs font-bold px-3 py-2 rounded-lg transition-all shadow-sm 
                                  ${expired 
                                    ? 'bg-green-600 hover:bg-green-700 shadow-green-200 cursor-pointer' 
                                    : 'bg-slate-300 cursor-not-allowed grayscale'}`}
                                title={!expired ? "Bu buton sadece iş saati geldiğinde aktif olur." : ""}
                              >
                                {expired ? <CheckCircle size={14} /> : <Lock size={14} />} 
                                Varış Onayla
                              </button>
                              <button 
                                onClick={() => handleDeleteScheduledJobAction(job)} 
                                className="p-2 text-slate-300 hover:text-red-500 transition-colors"
                              >
                                <Trash2 size={18} />
                              </button>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </section>

              {finishedJobs.length > 0 && (
                <section className="space-y-4 pt-4 border-t border-slate-200">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-bold text-slate-700 flex items-center gap-2">
                      <History size={20} />
                      Biten İşler (Arşiv)
                    </h2>
                    <button onClick={clearFinished} className="text-xs text-red-500 hover:underline">Temizle</button>
                  </div>
                  <div className="bg-white rounded-2xl border border-slate-200 divide-y divide-slate-100 opacity-75">
                    {finishedJobs.map(job => (
                      <div key={job.id} className="p-4 flex items-center justify-between">
                        <div className="text-sm">
                          <div className="font-bold text-slate-800">{job.passengerName}</div>
                          <div className="text-slate-500">{job.from} → {job.to} | {job.date}</div>
                        </div>
                        <div className="font-bold text-slate-600">{job.fee.toLocaleString('tr-TR')} ₺</div>
                      </div>
                    ))}
                  </div>
                </section>
              )}
            </div>
          </div>
        )}

        {view === 'stats' && (
          <StatsOverview jobs={jobs} scheduledJobs={scheduledJobs} expenses={expenses} />
        )}
      </main>
    </div>
  );
};

export default App;
