
export type ExpenseType = 'Köprü' | 'Gemi' | 'Yakıt' | 'Diğer';

export interface Job {
  id: string;
  company: string;
  from: string;
  to: string;
  amount: number;
  date: string; // ISO String
  timestamp: number;
  isAutoGenerated?: boolean;
}

export interface ScheduledJob {
  id: string;
  company: string;
  passengerName: string;
  from: string;
  to: string;
  fee: number;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
}

export interface Expense {
  id: string;
  type: ExpenseType;
  amount: number;
  date: string; // ISO String
}

export interface Stats {
  revenue: number;
  expenses: number;
  profit: number;
}

export interface SmsConfig {
  username: string;
  password: string;
  header: string;
  targetNumber: string;
  autoSend: boolean;
}

export interface SmsLog {
  jobId: string;
  slot: 'morning' | 'afternoon' | 'evening';
  date: string; // YYYY-MM-DD
}
