
export type ExpenseType = 'Köprü' | 'Gemi' | 'Yakıt' | 'Diğer';

export interface Job {
  id: string;
  company: string;
  from: string;
  to: string;
  amount: number;
  date: string; // ISO String
  timestamp: number;
  isAutoGenerated?: boolean;
}

export interface ScheduledJob {
  id: string;
  company: string;
  passengerName: string;
  from: string;
  to: string;
  fee: number;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
}

export interface Expense {
  id: string;
  type: ExpenseType;
  amount: number;
  date: string; // ISO String
}

export interface Stats {
  revenue: number;
  expenses: number;
  profit: number;
}

export interface TelegramConfig {
  botToken: string;
  chatId: string;
  autoSend: boolean;
}

export interface TelegramLog {
  date: string; // YYYY-MM-DD
  slot: string; // 'hour_0' ... 'hour_23' veya eski slotlar
}

export interface FlightInfo {
  flightNumber: string;
  status: string;
  departure: string;
  arrival: string;
  scheduledArrival: string;
  actualArrival: string;
  delay: string;
  gate: string;
  lastUpdated: string;
  sources?: { web: { uri: string; title: string } }[];
}
