
export type ExpenseType = 'Köprü' | 'Gemi' | 'Yakıt' | 'Diğer';

export interface Job {
  id: string;
  from: string;
  to: string;
  amount: number;
  date: string; // ISO String for day grouping
  timestamp: number;
  isAutoGenerated?: boolean; // Flag to identify jobs coming from scheduled
}

export interface ScheduledJob {
  id: string;
  passengerName: string;
  from: string;
  to: string;
  fee: number;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
}

export interface Expense {
  id: string;
  type: ExpenseType;
  amount: number;
  date: string; // ISO String
}

export interface Stats {
  revenue: number;
  expenses: number;
  profit: number;
}
